setting:
    sandbox         : false
    security_plugin : 0
    request_log     : false
    sql_log         : false
    timezone        : UTC
    cache_time      : 600
    secret_key      : xxxxxxxxxxxxxxxx

db_data:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4
    port        : 3306

db_backend:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4
    port        : 3306

db_log:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4
    port        : 3306

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

mq:
    host        :
    port        :
    username    :
    password    :
    vhost       :

sso:
    base_url    : http://www.example.com/api/sso/
    app_id      : 100