setting:
    sandbox         : false
    securityPlugin  : 0
    requestLog      : false
    recordSql       : false
    timezone        : UTC
    cacheTime       : 600
    cryptKey        : xxxxxxxxxxxxxxxx

db_data:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4
    port        : 3306

db_backend:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4
    port        : 3306

db_log:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4
    port        : 3306

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

mq:
    host        :
    port        :
    username    :
    password    :
    vhost       :

sso:
    BaseUrl     : http://www.example.com/api/sso/
    appId       : 100