setting:
    sandbox         : false
    securityPlugin  : 0
    recordRequest   : false
    recordSql       : false
    timezone        : UTC
    cacheTime       : 600
    cryptKey        : xxxxxxxxxxxxxxxx

application:
    controllersDir  : /app/controllers/
    modelsDir       : /app/models/
    viewsDir        : /app/views/
    servicesDir     : /app/services/
    pluginsDir      : /app/plugins/
    librariesDir    : /app/libraries/
    cacheDir        : /app/cache/
    logsDir         : /app/logs/
    baseUri         : /api/

db_data:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8
    port        : 3306

db_backend:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8
    port        : 3306

db_log:
    adapter     : Mysql
    host        : localhost
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8
    port        : 3306

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

sso:
    BaseUrl     : http://www.example.com/api/sso/
    appId       : 100